"""NutriOS — 'Did You Know?' Nutritional Tip Bank.

30 curated tips in 4 languages (EN, IT, ES, FR).
Each tip has category tags so the delivery service can pick
a contextual tip based on the user's recent food intake.
"""

NUTRITION_TIPS: dict[str, list[dict]] = {
    "en": [
        {"id": "tip_01", "cat": ["Fe", "synergy"], "title": "🧬 Did You Know?", "body": "Iron absorption increases up to 5x when paired with vitamin C. Add lemon to your spinach salad!"},
        {"id": "tip_02", "cat": ["Ca"], "title": "🧬 Did You Know?", "body": "Your body absorbs calcium better in small doses throughout the day — not all at once."},
        {"id": "tip_03", "cat": ["hydration"], "title": "🧬 Did You Know?", "body": "Even mild dehydration (2%) can reduce cognitive performance by 20%. Keep sipping!"},
        {"id": "tip_04", "cat": ["cooking"], "title": "🧬 Did You Know?", "body": "Steaming broccoli retains 90% of its vitamin C, while boiling loses up to 50%."},
        {"id": "tip_05", "cat": ["synergy"], "title": "🧬 Did You Know?", "body": "Turmeric's curcumin is 2000% more bioavailable when eaten with black pepper."},
        {"id": "tip_06", "cat": ["protein"], "title": "🧬 Did You Know?", "body": "Your body can only use ~25-30g of protein per meal for muscle building. Spread it across meals!"},
        {"id": "tip_07", "cat": ["Mg"], "title": "🧬 Did You Know?", "body": "Magnesium activates over 300 enzymes in your body. Dark chocolate is a surprisingly good source!"},
        {"id": "tip_08", "cat": ["K"], "title": "🧬 Did You Know?", "body": "Avocados have more potassium than bananas — 975mg vs 422mg per serving."},
        {"id": "tip_09", "cat": ["Zn"], "title": "🧬 Did You Know?", "body": "Pumpkin seeds pack 7mg of zinc per 100g — nearly your entire daily requirement."},
        {"id": "tip_10", "cat": ["fiber"], "title": "🧬 Did You Know?", "body": "Resistant starch in cooled rice feeds beneficial gut bacteria better than freshly cooked rice."},
        {"id": "tip_11", "cat": ["cooking"], "title": "🧬 Did You Know?", "body": "Garlic's beneficial allicin is maximized by crushing and waiting 10 min before cooking."},
        {"id": "tip_12", "cat": ["Ca", "synergy"], "title": "🧬 Did You Know?", "body": "Vitamin D boosts calcium absorption by up to 65%. Pair dairy with fatty fish or sunlight!"},
        {"id": "tip_13", "cat": ["fat"], "title": "🧬 Did You Know?", "body": "The omega-3 in walnuts reduces inflammation markers. Just 7 walnuts = your daily dose."},
        {"id": "tip_14", "cat": ["Fe", "cooking"], "title": "🧬 Did You Know?", "body": "Cooking in cast iron can increase your food's iron content by up to 16x."},
        {"id": "tip_15", "cat": ["hydration"], "title": "🧬 Did You Know?", "body": "Water-rich foods (cucumber, watermelon) contribute about 20% of your daily hydration."},
        {"id": "tip_16", "cat": ["protein"], "title": "🧬 Did You Know?", "body": "Quinoa is one of the few plant foods with all 9 essential amino acids — a complete protein!"},
        {"id": "tip_17", "cat": ["cooking"], "title": "🧬 Did You Know?", "body": "Microwaving vegetables actually preserves more nutrients than most other cooking methods."},
        {"id": "tip_18", "cat": ["fat", "synergy"], "title": "🧬 Did You Know?", "body": "Fat-soluble vitamins (A, D, E, K) need dietary fat to absorb. Add olive oil to your salad!"},
        {"id": "tip_19", "cat": ["Ca"], "title": "🧬 Did You Know?", "body": "Kale has more calcium per calorie than milk. One cup of kale = 100mg of calcium."},
        {"id": "tip_20", "cat": ["Mg"], "title": "🧬 Did You Know?", "body": "Low magnesium is linked to poor sleep quality. Try almonds or a banana before bed."},
        {"id": "tip_21", "cat": ["K"], "title": "🧬 Did You Know?", "body": "Too little potassium is more common — and more dangerous — than too much sodium."},
        {"id": "tip_22", "cat": ["fiber"], "title": "🧬 Did You Know?", "body": "Eating 30 different plants per week dramatically improves gut microbiome diversity."},
        {"id": "tip_23", "cat": ["cooking"], "title": "🧬 Did You Know?", "body": "Tomatoes release more lycopene when cooked — tomato sauce is more nutritious than raw tomato!"},
        {"id": "tip_24", "cat": ["synergy"], "title": "🧬 Did You Know?", "body": "Green tea polyphenols boost your metabolism by 4-5% when naturally paired with its caffeine."},
        {"id": "tip_25", "cat": ["hydration"], "title": "🧬 Did You Know?", "body": "Your brain is 75% water. A single glass of water can boost focus within 20 minutes."},
        {"id": "tip_26", "cat": ["protein"], "title": "🧬 Did You Know?", "body": "Greek yogurt has 2x the protein of regular yogurt — up to 20g per cup."},
        {"id": "tip_27", "cat": ["Zn", "synergy"], "title": "🧬 Did You Know?", "body": "Zinc + vitamin C together supercharge immune function. Try an orange with pumpkin seeds!"},
        {"id": "tip_28", "cat": ["fat", "synergy"], "title": "🧬 Did You Know?", "body": "Adding avocado to a salad increases absorption of fat-soluble antioxidants by up to 15x."},
        {"id": "tip_29", "cat": ["Fe"], "title": "🧬 Did You Know?", "body": "Tea and coffee can reduce iron absorption by 60%. Wait 1 hour after meals before drinking them."},
        {"id": "tip_30", "cat": ["cooking"], "title": "🧬 Did You Know?", "body": "Freezing blueberries actually makes their antioxidants MORE available to your body."},
    ],
    "it": [
        {"id": "tip_01", "cat": ["Fe", "synergy"], "title": "🧬 Lo Sapevi?", "body": "L'assorbimento del ferro aumenta fino a 5 volte con la vitamina C. Aggiungi limone ai tuoi spinaci!"},
        {"id": "tip_02", "cat": ["Ca"], "title": "🧬 Lo Sapevi?", "body": "Il tuo corpo assorbe meglio il calcio in piccole dosi durante la giornata, non tutto in una volta."},
        {"id": "tip_03", "cat": ["hydration"], "title": "🧬 Lo Sapevi?", "body": "Anche una lieve disidratazione (2%) può ridurre le prestazioni cognitive del 20%. Continua a bere!"},
        {"id": "tip_04", "cat": ["cooking"], "title": "🧬 Lo Sapevi?", "body": "Cuocere i broccoli al vapore conserva il 90% della vitamina C, mentre bollirli ne perde fino al 50%."},
        {"id": "tip_05", "cat": ["synergy"], "title": "🧬 Lo Sapevi?", "body": "La curcumina della curcuma è 2000% più biodisponibile se mangiata con pepe nero."},
        {"id": "tip_06", "cat": ["protein"], "title": "🧬 Lo Sapevi?", "body": "Il corpo usa solo ~25-30g di proteine per pasto per la sintesi muscolare. Distribuiscile nei pasti!"},
        {"id": "tip_07", "cat": ["Mg"], "title": "🧬 Lo Sapevi?", "body": "Il magnesio attiva oltre 300 enzimi. Il cioccolato fondente è una fonte sorprendentemente buona!"},
        {"id": "tip_08", "cat": ["K"], "title": "🧬 Lo Sapevi?", "body": "Gli avocado hanno più potassio delle banane — 975mg contro 422mg per porzione."},
        {"id": "tip_09", "cat": ["Zn"], "title": "🧬 Lo Sapevi?", "body": "I semi di zucca contengono 7mg di zinco per 100g — quasi il tuo fabbisogno giornaliero!"},
        {"id": "tip_10", "cat": ["fiber"], "title": "🧬 Lo Sapevi?", "body": "L'amido resistente nel riso raffreddato nutre i batteri intestinali meglio del riso appena cotto."},
        {"id": "tip_11", "cat": ["cooking"], "title": "🧬 Lo Sapevi?", "body": "L'allicina dell'aglio si massimizza schiacciandolo e aspettando 10 minuti prima di cuocerlo."},
        {"id": "tip_12", "cat": ["Ca", "synergy"], "title": "🧬 Lo Sapevi?", "body": "La vitamina D aumenta l'assorbimento del calcio fino al 65%. Abbina latticini a pesce grasso!"},
        {"id": "tip_13", "cat": ["fat"], "title": "🧬 Lo Sapevi?", "body": "Gli omega-3 delle noci riducono i marcatori infiammatori. Solo 7 noci = la dose giornaliera."},
        {"id": "tip_14", "cat": ["Fe", "cooking"], "title": "🧬 Lo Sapevi?", "body": "Cucinare in padella di ghisa può aumentare il contenuto di ferro del cibo fino a 16 volte."},
        {"id": "tip_15", "cat": ["hydration"], "title": "🧬 Lo Sapevi?", "body": "Cibi ricchi d'acqua (cetriolo, anguria) contribuiscono al 20% dell'idratazione giornaliera."},
        {"id": "tip_16", "cat": ["protein"], "title": "🧬 Lo Sapevi?", "body": "La quinoa è uno dei pochi alimenti vegetali con tutti i 9 aminoacidi essenziali!"},
        {"id": "tip_17", "cat": ["cooking"], "title": "🧬 Lo Sapevi?", "body": "Il microonde conserva più nutrienti nelle verdure rispetto alla maggior parte dei metodi di cottura."},
        {"id": "tip_18", "cat": ["fat", "synergy"], "title": "🧬 Lo Sapevi?", "body": "Le vitamine liposolubili (A, D, E, K) necessitano di grassi per essere assorbite. Aggiungi olio d'oliva!"},
        {"id": "tip_19", "cat": ["Ca"], "title": "🧬 Lo Sapevi?", "body": "Il cavolo riccio ha più calcio per caloria del latte. Una tazza = 100mg di calcio."},
        {"id": "tip_20", "cat": ["Mg"], "title": "🧬 Lo Sapevi?", "body": "Il magnesio basso è collegato a scarsa qualità del sonno. Prova mandorle o banana prima di dormire."},
        {"id": "tip_21", "cat": ["K"], "title": "🧬 Lo Sapevi?", "body": "La carenza di potassio è più comune e pericolosa dell'eccesso di sodio."},
        {"id": "tip_22", "cat": ["fiber"], "title": "🧬 Lo Sapevi?", "body": "Mangiare 30 piante diverse a settimana migliora notevolmente la diversità del microbioma intestinale."},
        {"id": "tip_23", "cat": ["cooking"], "title": "🧬 Lo Sapevi?", "body": "I pomodori rilasciano più licopene da cotti — il sugo è più nutriente del pomodoro crudo!"},
        {"id": "tip_24", "cat": ["synergy"], "title": "🧬 Lo Sapevi?", "body": "I polifenoli del tè verde aumentano il metabolismo del 4-5% in combinazione con la caffeina."},
        {"id": "tip_25", "cat": ["hydration"], "title": "🧬 Lo Sapevi?", "body": "Il cervello è composto per il 75% da acqua. Un bicchiere d'acqua migliora la concentrazione in 20 minuti."},
        {"id": "tip_26", "cat": ["protein"], "title": "🧬 Lo Sapevi?", "body": "Lo yogurt greco ha il doppio delle proteine rispetto a quello normale — fino a 20g per tazza."},
        {"id": "tip_27", "cat": ["Zn", "synergy"], "title": "🧬 Lo Sapevi?", "body": "Zinco + vitamina C insieme potenziano il sistema immunitario. Prova un'arancia con semi di zucca!"},
        {"id": "tip_28", "cat": ["fat", "synergy"], "title": "🧬 Lo Sapevi?", "body": "Aggiungere avocado all'insalata aumenta l'assorbimento degli antiossidanti fino a 15 volte."},
        {"id": "tip_29", "cat": ["Fe"], "title": "🧬 Lo Sapevi?", "body": "Tè e caffè riducono l'assorbimento del ferro del 60%. Aspetta 1 ora dopo i pasti per berli."},
        {"id": "tip_30", "cat": ["cooking"], "title": "🧬 Lo Sapevi?", "body": "Congelare i mirtilli rende i loro antiossidanti PIÙ disponibili per il corpo."},
    ],
    "es": [
        {"id": "tip_01", "cat": ["Fe", "synergy"], "title": "🧬 ¿Sabías Que?", "body": "¡La absorción de hierro aumenta hasta 5 veces con vitamina C! Añade limón a tus espinacas."},
        {"id": "tip_02", "cat": ["Ca"], "title": "🧬 ¿Sabías Que?", "body": "Tu cuerpo absorbe mejor el calcio en pequeñas dosis a lo largo del día, no todo de una vez."},
        {"id": "tip_03", "cat": ["hydration"], "title": "🧬 ¿Sabías Que?", "body": "Incluso una deshidratación leve (2%) puede reducir el rendimiento cognitivo un 20%. ¡Sigue bebiendo!"},
        {"id": "tip_04", "cat": ["cooking"], "title": "🧬 ¿Sabías Que?", "body": "Cocinar brócoli al vapor conserva el 90% de su vitamina C; hervirlo pierde hasta el 50%."},
        {"id": "tip_05", "cat": ["synergy"], "title": "🧬 ¿Sabías Que?", "body": "La curcumina de la cúrcuma es 2000% más biodisponible si se come con pimienta negra."},
        {"id": "tip_06", "cat": ["protein"], "title": "🧬 ¿Sabías Que?", "body": "Tu cuerpo solo usa ~25-30g de proteína por comida para construir músculo. ¡Distribúyela!"},
        {"id": "tip_07", "cat": ["Mg"], "title": "🧬 ¿Sabías Que?", "body": "El magnesio activa más de 300 enzimas. ¡El chocolate oscuro es una fuente sorprendentemente buena!"},
        {"id": "tip_08", "cat": ["K"], "title": "🧬 ¿Sabías Que?", "body": "Los aguacates tienen más potasio que los plátanos — 975mg vs 422mg por porción."},
        {"id": "tip_09", "cat": ["Zn"], "title": "🧬 ¿Sabías Que?", "body": "Las semillas de calabaza tienen 7mg de zinc por 100g — ¡casi tu requerimiento diario completo!"},
        {"id": "tip_10", "cat": ["fiber"], "title": "🧬 ¿Sabías Que?", "body": "El almidón resistente del arroz enfriado alimenta las bacterias intestinales mejor que el arroz recién cocido."},
        {"id": "tip_11", "cat": ["cooking"], "title": "🧬 ¿Sabías Que?", "body": "La alicina del ajo se maximiza aplastándolo y esperando 10 minutos antes de cocinarlo."},
        {"id": "tip_12", "cat": ["Ca", "synergy"], "title": "🧬 ¿Sabías Que?", "body": "La vitamina D aumenta la absorción de calcio hasta un 65%. ¡Combina lácteos con pescado graso!"},
        {"id": "tip_13", "cat": ["fat"], "title": "🧬 ¿Sabías Que?", "body": "Los omega-3 de las nueces reducen los marcadores de inflamación. Solo 7 nueces = tu dosis diaria."},
        {"id": "tip_14", "cat": ["Fe", "cooking"], "title": "🧬 ¿Sabías Que?", "body": "Cocinar en sartén de hierro fundido puede aumentar el contenido de hierro del alimento hasta 16 veces."},
        {"id": "tip_15", "cat": ["hydration"], "title": "🧬 ¿Sabías Que?", "body": "Alimentos ricos en agua (pepino, sandía) contribuyen al 20% de tu hidratación diaria."},
        {"id": "tip_16", "cat": ["protein"], "title": "🧬 ¿Sabías Que?", "body": "La quinoa es uno de los pocos alimentos vegetales con los 9 aminoácidos esenciales — ¡proteína completa!"},
        {"id": "tip_17", "cat": ["cooking"], "title": "🧬 ¿Sabías Que?", "body": "El microondas conserva más nutrientes en las verduras que la mayoría de métodos de cocción."},
        {"id": "tip_18", "cat": ["fat", "synergy"], "title": "🧬 ¿Sabías Que?", "body": "Las vitaminas liposolubles (A, D, E, K) necesitan grasa para absorberse. ¡Añade aceite de oliva!"},
        {"id": "tip_19", "cat": ["Ca"], "title": "🧬 ¿Sabías Que?", "body": "La col rizada tiene más calcio por caloría que la leche. Una taza = 100mg de calcio."},
        {"id": "tip_20", "cat": ["Mg"], "title": "🧬 ¿Sabías Que?", "body": "El magnesio bajo se asocia con mala calidad del sueño. Prueba almendras o plátano antes de dormir."},
        {"id": "tip_21", "cat": ["K"], "title": "🧬 ¿Sabías Que?", "body": "La falta de potasio es más común y peligrosa que el exceso de sodio."},
        {"id": "tip_22", "cat": ["fiber"], "title": "🧬 ¿Sabías Que?", "body": "Comer 30 plantas distintas por semana mejora enormemente la diversidad del microbioma intestinal."},
        {"id": "tip_23", "cat": ["cooking"], "title": "🧬 ¿Sabías Que?", "body": "Los tomates liberan más licopeno al cocinarse — ¡la salsa de tomate es más nutritiva que el tomate crudo!"},
        {"id": "tip_24", "cat": ["synergy"], "title": "🧬 ¿Sabías Que?", "body": "Los polifenoles del té verde aumentan tu metabolismo un 4-5% combinados con su cafeína natural."},
        {"id": "tip_25", "cat": ["hydration"], "title": "🧬 ¿Sabías Que?", "body": "Tu cerebro es 75% agua. Un vaso de agua puede mejorar la concentración en 20 minutos."},
        {"id": "tip_26", "cat": ["protein"], "title": "🧬 ¿Sabías Que?", "body": "El yogur griego tiene el doble de proteínas que el normal — hasta 20g por taza."},
        {"id": "tip_27", "cat": ["Zn", "synergy"], "title": "🧬 ¿Sabías Que?", "body": "Zinc + vitamina C juntos potencian el sistema inmune. ¡Prueba una naranja con semillas de calabaza!"},
        {"id": "tip_28", "cat": ["fat", "synergy"], "title": "🧬 ¿Sabías Que?", "body": "Añadir aguacate a una ensalada aumenta la absorción de antioxidantes liposolubles hasta 15 veces."},
        {"id": "tip_29", "cat": ["Fe"], "title": "🧬 ¿Sabías Que?", "body": "El té y el café pueden reducir la absorción de hierro un 60%. Espera 1 hora después de comer."},
        {"id": "tip_30", "cat": ["cooking"], "title": "🧬 ¿Sabías Que?", "body": "Congelar los arándanos hace que sus antioxidantes sean MÁS disponibles para tu cuerpo."},
    ],
    "fr": [
        {"id": "tip_01", "cat": ["Fe", "synergy"], "title": "🧬 Le Saviez-Vous ?", "body": "L'absorption du fer augmente jusqu'à 5 fois avec la vitamine C. Ajoutez du citron à vos épinards !"},
        {"id": "tip_02", "cat": ["Ca"], "title": "🧬 Le Saviez-Vous ?", "body": "Votre corps absorbe mieux le calcium en petites doses tout au long de la journée."},
        {"id": "tip_03", "cat": ["hydration"], "title": "🧬 Le Saviez-Vous ?", "body": "Même une légère déshydratation (2%) peut réduire les performances cognitives de 20%. Continuez à boire !"},
        {"id": "tip_04", "cat": ["cooking"], "title": "🧬 Le Saviez-Vous ?", "body": "Cuire le brocoli à la vapeur conserve 90% de sa vitamine C ; le bouillir en perd jusqu'à 50%."},
        {"id": "tip_05", "cat": ["synergy"], "title": "🧬 Le Saviez-Vous ?", "body": "La curcumine du curcuma est 2000% plus biodisponible quand elle est mangée avec du poivre noir."},
        {"id": "tip_06", "cat": ["protein"], "title": "🧬 Le Saviez-Vous ?", "body": "Le corps n'utilise que ~25-30g de protéines par repas pour la synthèse musculaire. Répartissez-les !"},
        {"id": "tip_07", "cat": ["Mg"], "title": "🧬 Le Saviez-Vous ?", "body": "Le magnésium active plus de 300 enzymes. Le chocolat noir est une source étonnamment bonne !"},
        {"id": "tip_08", "cat": ["K"], "title": "🧬 Le Saviez-Vous ?", "body": "Les avocats contiennent plus de potassium que les bananes — 975mg contre 422mg par portion."},
        {"id": "tip_09", "cat": ["Zn"], "title": "🧬 Le Saviez-Vous ?", "body": "Les graines de courge contiennent 7mg de zinc pour 100g — presque votre besoin quotidien !"},
        {"id": "tip_10", "cat": ["fiber"], "title": "🧬 Le Saviez-Vous ?", "body": "L'amidon résistant du riz refroidi nourrit les bactéries intestinales mieux que le riz fraîchement cuit."},
        {"id": "tip_11", "cat": ["cooking"], "title": "🧬 Le Saviez-Vous ?", "body": "L'allicine de l'ail est maximisée en l'écrasant et en attendant 10 min avant de cuisiner."},
        {"id": "tip_12", "cat": ["Ca", "synergy"], "title": "🧬 Le Saviez-Vous ?", "body": "La vitamine D augmente l'absorption du calcium jusqu'à 65%. Associez les produits laitiers au poisson gras !"},
        {"id": "tip_13", "cat": ["fat"], "title": "🧬 Le Saviez-Vous ?", "body": "Les oméga-3 des noix réduisent les marqueurs d'inflammation. 7 noix = votre dose quotidienne."},
        {"id": "tip_14", "cat": ["Fe", "cooking"], "title": "🧬 Le Saviez-Vous ?", "body": "Cuisiner dans une poêle en fonte peut augmenter la teneur en fer des aliments jusqu'à 16 fois."},
        {"id": "tip_15", "cat": ["hydration"], "title": "🧬 Le Saviez-Vous ?", "body": "Les aliments riches en eau (concombre, pastèque) contribuent à environ 20% de l'hydratation quotidienne."},
        {"id": "tip_16", "cat": ["protein"], "title": "🧬 Le Saviez-Vous ?", "body": "Le quinoa est l'un des rares aliments végétaux contenant les 9 acides aminés essentiels !"},
        {"id": "tip_17", "cat": ["cooking"], "title": "🧬 Le Saviez-Vous ?", "body": "Le micro-ondes préserve plus de nutriments dans les légumes que la plupart des autres méthodes."},
        {"id": "tip_18", "cat": ["fat", "synergy"], "title": "🧬 Le Saviez-Vous ?", "body": "Les vitamines liposolubles (A, D, E, K) ont besoin de graisses pour être absorbées. Ajoutez de l'huile d'olive !"},
        {"id": "tip_19", "cat": ["Ca"], "title": "🧬 Le Saviez-Vous ?", "body": "Le chou kale contient plus de calcium par calorie que le lait. Une tasse = 100mg de calcium."},
        {"id": "tip_20", "cat": ["Mg"], "title": "🧬 Le Saviez-Vous ?", "body": "Un faible taux de magnésium est lié à un mauvais sommeil. Essayez des amandes avant de dormir."},
        {"id": "tip_21", "cat": ["K"], "title": "🧬 Le Saviez-Vous ?", "body": "Le manque de potassium est plus courant et plus dangereux que l'excès de sodium."},
        {"id": "tip_22", "cat": ["fiber"], "title": "🧬 Le Saviez-Vous ?", "body": "Manger 30 plantes différentes par semaine améliore considérablement la diversité du microbiome."},
        {"id": "tip_23", "cat": ["cooking"], "title": "🧬 Le Saviez-Vous ?", "body": "Les tomates libèrent plus de lycopène cuites — la sauce tomate est plus nutritive que la tomate crue !"},
        {"id": "tip_24", "cat": ["synergy"], "title": "🧬 Le Saviez-Vous ?", "body": "Les polyphénols du thé vert augmentent le métabolisme de 4-5% combinés à sa caféine naturelle."},
        {"id": "tip_25", "cat": ["hydration"], "title": "🧬 Le Saviez-Vous ?", "body": "Votre cerveau est composé à 75% d'eau. Un verre d'eau améliore la concentration en 20 minutes."},
        {"id": "tip_26", "cat": ["protein"], "title": "🧬 Le Saviez-Vous ?", "body": "Le yaourt grec contient 2 fois plus de protéines que le yaourt classique — jusqu'à 20g par tasse."},
        {"id": "tip_27", "cat": ["Zn", "synergy"], "title": "🧬 Le Saviez-Vous ?", "body": "Zinc + vitamine C ensemble renforcent le système immunitaire. Essayez une orange avec des graines de courge !"},
        {"id": "tip_28", "cat": ["fat", "synergy"], "title": "🧬 Le Saviez-Vous ?", "body": "Ajouter de l'avocat à une salade augmente l'absorption des antioxydants liposolubles jusqu'à 15 fois."},
        {"id": "tip_29", "cat": ["Fe"], "title": "🧬 Le Saviez-Vous ?", "body": "Le thé et le café réduisent l'absorption du fer de 60%. Attendez 1 heure après les repas."},
        {"id": "tip_30", "cat": ["cooking"], "title": "🧬 Le Saviez-Vous ?", "body": "Congeler les myrtilles rend leurs antioxydants PLUS disponibles pour votre corps."},
    ],
}
